### DISCUSSION TITLE
Auto sort Regular / UNL88 by price on dashboard

### DISCUSSION THREAD

**Discussion by dudenell** [firstof9/ha-gasbuddy#131] [Show and tell]
I wanted to say Thank you to @firstof9 for making this integration

Here's my Gas Dashboard
![image](https://github.com/user-attachments/assets/691d68c1-a546-4e97-ada4-8f5e5c0934a8)

Needed to install https://github.com/thomasloven/lovelace-auto-entities

I added each individual gas station through the Gas Buddy Integration, when adding I assigned them Area's based on geographical location.

Below is my yaml for one area:

```yaml
type: custom:auto-entities
card:
  type: entities
  title: Gas Station Prices Apex (Regular / UNL88)
filter:
  include:
    - domain: sensor
      area: Gas Stations Apex
      name: (*Regular*|*UNL88*)
  exclude:
    - state: unavailable
  sort:
    method: state
    numeric: true
show_empty: false
sort:
  method: state
  numeric: true
```
