### ISSUE TITLE
[Feature Request]: City/zipcode prices

### ISSUE THREAD

**Issue by tankdeer** [firstof9/ha-gasbuddy#140]
### The feature

Although they are currently broken due to Gas Buddy's API changes, two of the REST sensors I had setup previously, in addition to individual station sensors, was an "Average Price" and a "Lowest Price" sensor for my city. I had these along with the two closest stations to my house in an Apexcharts graph. It was convenient in not only allowing me to see the prices at the stations I frequent most often, but how they compare to others in the area. The "Lowest Price" sensor stored the station details as an attribute if I really wanted to know where it was.

It would be awesome if we could do something similar through your integration. Thanks!

### Additional information

Thank you for this awesome integration. You've made two of my complex rest sensors obsolete. Two to go. 😁🎉

**Comment by firstof9** [comment]
Can you post your REST sensor for this, I'll see what I can whip up for ya.

**Comment by tankdeer** [comment]
Sorry for the delay, here's what I got. It's actually one REST sensor that returns a list of gas stations in the area, and then two template sensors to extract the data needed from them. It's a bit messy, but was functional until they changed the graphql api.

In my case I was only interested in Premium fuel prices, but it should be more or less the same for them all

REST:
```
- platform: rest
  unique_id: gas_stations_search
  name: Gas Station Search
  icon: mdi:gas-station
  scan_interval: 14400 # Every 4 hours. Individual gas stations are hourly but this should be enough for average/low
  resource: https://www.gasbuddy.com/graphql
  method: POST
  headers:
    Content-Type: application/json
  payload: >
    {
      "operationName": "LocationBySearchTerm",
      "variables": {
          "fuel": 2,
          "maxAge": 0,
          "search": "Portland, OR"
      },
      "query": "query LocationBySearchTerm($brandId: Int, $cursor: String, $maxAge: Int, $search: String) { locationBySearchTerm(search: $search) { stations(brandId: $brandId, cursor: $cursor, maxAge: $maxAge) { count cursor { next } results {  address { country line1 line2 locality postalCode region }  fuels id name prices { cash { nickname postedTime price } credit { nickname postedTime price } } } } trends { areaName country today todayLow trend } }}"
    }
  state_class: measurement
  unit_of_measurement: USD
  value_template: "{{ value_json.data.locationBySearchTerm.trends.0.today }}"
  json_attributes_path: "$.data.locationBySearchTerm"
  json_attributes:
    - stations
    - trends
```

Lowest Price extracted from the previous REST sensor `stations` attribute:
```
- trigger:
    - platform: state
      entity_id: sensor.gas_station_search
    - platform: time_pattern
      minutes: 0
  sensor:
    - unique_id: lowest_gas_price_premium
      name: Lowest Gas Price (Premium)
      icon: mdi:gas-station
      unit_of_measurement: USD
      state_class: measurement
      state: >-
        {% set vars = namespace(price=0) %}
        {% for price_details in this.attributes.prices | default([]) %}
          {% if price_details.get('cash') != None
            and price_details.get('cash') > 0
            and (vars.price == 0 or price_details.get('cash') < vars.price) %}
            {% set vars.price = price_details.get('cash') %}
          {% endif %}
          {% if price_details.get('credit') != None
            and price_details.get('credit') > 0
            and (vars.price == 0 or price_details.get('credit') < vars.price) %}
            {% set vars.price = price_details.get('credit') %}
          {% endif %}
        {% endfor %}
        {{ vars.price if vars.price > 0 else this.state }}
      attributes:
        prices: >
          {% set vars = namespace(prices=[]) %}
          {% set stations = state_attr('sensor.gas_station_search', 'stations') %}
          {% if stations != None and stations.results != None %}
            {% for result in stations.results %}
              {% for fuel in result.fuels %}
                {% if fuel == 'premium_gas' %}
                  {# Store information about this fuel type for use in other attributes below. #}
                  {% set fuel_vars = namespace(index=loop.index-1, details='') %}
                  {% if fuel_vars.index < result.prices | length %}
                    {% if result.prices[fuel_vars.index].cash != None and result.prices[fuel_vars.index].cash.price > 0 %}
                      {% set fuel_vars.details = fuel_vars.details + "\"cash\" : " + result.prices[fuel_vars.index].cash.price|string  %}
                    {% endif %}
                    {% if result.prices[fuel_vars.index].credit != None and result.prices[fuel_vars.index].credit.price > 0 %}
                      {% if fuel_vars.details | length > 0 %}
                        {% set fuel_vars.details = fuel_vars.details + "," %}
                      {% endif %}
                      {% set fuel_vars.details = fuel_vars.details + "\"credit\" : " + result.prices[fuel_vars.index].credit.price|string %}
                    {% endif %}
                    {% if fuel_vars.details | length > 0 %}
                      {% set additional_details =
                        "\"station\" : {" +
                          "\"id\" : " + result.id|string + "," +
                          "\"name\" : \"" + result.name + "\""
                        "}," +
                        "\"address\" : {" +
                          "\"line1\" : \"" + result.address.line1 + "\"," +
                          "\"line2\" : \"" + result.address.line2 + "\"," +
                          "\"locality\" : \"" + result.address.locality + "\"," +
                          "\"postal_code\" : \"" + result.address.postalCode + "\"," +
                          "\"region\" : \"" + result.address.region + "\"" +
                        "}" %}
                      {% set fuel_vars.details = additional_details + "," + fuel_vars.details %}
                    {% endif %}
                  {% endif %}
                  {% if fuel_vars.details | length > 0 %}
                    {% set vars.prices = vars.prices + [ ('{' + fuel_vars.details + '}') | from_json ]  %}
                  {% endif %}
                {% endif %}
              {%endfor%}
            {% endfor %}
          {% endif %}
          {{ vars.prices }}
        lowest_price_details: >
          {% set vars = namespace(price=0, lowest_price_details=None) %}
          {% for price_details in this.attributes.prices | default([]) %}
            {% if vars.lowest_price_details == None %}
              {% set vars.lowest_price_details = price_details %}
            {% endif %}
            {% if price_details.get('cash') != None
              and (vars.price == 0 or price_details.get('cash') < vars.price) %}
              {% set vars.price = price_details.get('cash') %}
              {% set vars.lowest_price_details = price_details %}
            {% endif %}
            {% if price_details.get('credit') != None
              and (vars.price == 0 or price_details.get('credit') < vars.price) %}
              {% set vars.price = price_details.get('credit') %}
              {% set vars.lowest_price_details = price_details %}
            {% endif %}
          {% endfor %}
          {{ vars.lowest_price_details }}
```

Lastly, the average price sensor. I believe the `trends` attribute in the json response on the rest actually has the average for Regular fuel, but again I was interested in Premium, so I came up with this
```
- trigger:
    - platform: state
      entity_id: sensor.gas_station_search
    - platform: time_pattern
      minutes: 0
  sensor:
    - unique_id: average_gas_price_premium
      name: Average Gas Price (Premium)
      icon: mdi:gas-station
      unit_of_measurement: USD
      state_class: measurement
      state: >
         {{ average(this.attributes.prices, default=this.state) | round(2) }}
      attributes:
        prices: >
         {% set vars = namespace(prices=[]) -%}
          {% set stations = state_attr('sensor.gas_station_search', 'stations') -%}
          {% if stations != None and stations.results != None -%}
            {% for result in stations.results -%}
              {% for fuel in result.fuels -%}
                {% if fuel == 'premium_gas' -%}
                  {% set fuel_vars = namespace(index=loop.index-1, current=0) -%}
                  {% if fuel_vars.index < result.prices | length -%}
                    {% set fuel_vars.current = result.prices[fuel_vars.index].cash -%}
                    {% if fuel_vars.current != None and fuel_vars.current.price > 0 -%}
                      {% set vars.prices = vars.prices + [ (fuel_vars.current.price) ]  -%}
                    {% endif -%}
                    {% set fuel_vars.current = result.prices[fuel_vars.index].credit -%}
                    {% if fuel_vars.current != None and fuel_vars.current.price > 0 -%}
                      {% set vars.prices = vars.prices + [ (fuel_vars.current.price ) ]  -%}
                    {% endif -%}
                  {% endif -%}
                {% endif -%}
              {% endfor -%}
            {% endfor -%}
          {% endif -%}
          {{ vars.prices }}
```

**Comment by tankdeer** [comment]
Awesome, thank you. I'm sure it could be simplified a lot

**Comment by Dare2Code** [comment]
Yeah, I had a similar YAML script:

This gives me 'Lowest gas' price and 'Average Gas' price.

`- scan_interval: 600
  resource: https://www.gasbuddy.com/graphql
  method: POST
  headers:
    Content-Type: application/json
  payload: |
    {
      "operationName": "LocationBySearchTerm",
      "variables": {
        "fuel": 1,
        "maxAge": 0,
        "search": "K1G4L5"
      },
      "query": "query LocationBySearchTerm($search: String) { locationBySearchTerm(search: $search) { trends { areaName country today todayLow } } }"
    }
  sensor:
    - unique_id: gasbuddy_lowest_gas_price
      name: Gasbuddy Lowest Gas Price
      icon: mdi:gas-station
      unit_of_measurement: ¢
      value_template: "{{ value_json.data.locationBySearchTerm.trends.0.today | float }}"
    - unique_id: gasbuddy_average_gas_price
      name: Gasbuddy Average Gas Price
      icon: mdi:gas-station
      unit_of_measurement: ¢
      value_template: "{{ value_json.data.locationBySearchTerm.trends.0.todayLow | float }}"
`

**Comment by firstof9** [comment]
1.0.23-b0 has an action you can call to parse the api output into template sensors that replaces the REST calls.
Can you see if this helps you at all?

**Comment by tankdeer** [comment]
Interesting, thank you. I will have to play with this a bit. I did call it from dev tools to get a feel for how it looks - will have to rewrite my sensors to parse the data.

I assume that creating the sensors directly via this integration is not practical?

**Comment by firstof9** [comment]
Since we're only tracking specific stations for pricing data, yes, it's not really feasible at this time.

**Comment by firstof9** [comment]
> Is there a way to set a radius or more city-wide search than a single zipcode?

I honestly am not sure how wide the default search goes with the zipcode. If you find it not wide enough please let me know, I can see about adding a service for city searches.

**Comment by tankdeer** [comment]
Haven't really had time to play with this today. I did realize that even with your action you can enter a city/state combo in place of zipcode and it works. The results are different, presumably the city would be based on the city center vs an individual zip.

In both cases, I only got 5 results back, which I am not sure is really enough to get valuable info for as far as average & lowest price. If we can figure out how to expand it, that would be awesome

**Comment by tankdeer** [comment]
Awesome, thank you. That bumps the results up to 20, which I am guessing is a limit on gas buddy's side and not yours. Using this new action, I added the following template sensors. This gives me average & lowest for premium & regular and is infinitely cleaner than the old sensors. Thanks again for adding this.

```
- trigger:
    - platform: time_pattern
      hours: /4
  action:
    - action: gasbuddy.lookup_zip
      data:
        zipcode: Portland, OR
        limit: 99
      response_variable: response
    - variables:
        premium_list: >
          {%- set vars = namespace(prices=[]) -%}
          {%- for station in response['results'] if station.premium_gas.price is number -%}
            {%- set vars.prices = vars.prices + [ (station.premium_gas.price) ] -%}
          {%- endfor -%}
          {{ vars.prices }}
  sensor:
    - name: Average Gas Price (Premium)
      unique_id: average_gas_price_premium
      icon: mdi:gas-station
      unit_of_measurement: USD
      state_class: measurement
      state: >
         {{ average(premium_list) | round(2) }}
    - name: Lowest Gas Price (Premium)
      unique_id: lowest_gas_price_premium
      icon: mdi:gas-station
      unit_of_measurement: USD
      state_class: measurement
      state: >
        {{ min(premium_list) }}
    - name: Average Gas Price (Regular)
      unique_id: average_gas_price_regular
      icon: mdi:gas-station
      unit_of_measurement: USD
      state_class: measurement
      state: >
         {{ response.trend.average_price }}
    - name: Lowest Gas Price (Regular)
      unique_id: lowest_gas_price_regular
      icon: mdi:gas-station
      unit_of_measurement: USD
      state_class: measurement
      state: >
        {{ response.trend.lowest_price }}
```

**Comment by firstof9** [comment]
> Thanks again for adding this.

Thank you for testing 👍

**Comment by firstof9** [comment]
@Dare2Code were you able to adjust your templates as well?

**Comment by Dare2Code** [comment]
I've moved on and started using this link to show a chart that gets auto refreshed:
https://charts.gasbuddy.com/ch.gaschart?Country=USA&Crude=f&Period=1&Areas=Ottawa%2COntario%2C&Unit=Canadian%20c%2FL

I did notice if i use this below action, i do see a 'trend' data down below, that's exactly what we've wanted.

```
action: gasbuddy.lookup_zip
data:
  zipcode: Ottawa, ON
  limit: 1
```

Results:

```
results:
  - station_id: "60025"
    unit_of_measure: cents_per_liter
    currency: CAD
    latitude: 45.029831868764
    longitude: -75.637350082397
    regular_gas:
      credit: Thea2012
      price: 127.9
      last_updated: "2025-04-01T16:05:26.381Z"
    midgrade_gas:
      credit: mthornto1956
      price: 145.9
      last_updated: "2025-04-01T12:01:49.538Z"
    premium_gas:
      credit: mthornto1956
      price: 151.9
      last_updated: "2025-04-01T12:01:49.569Z"
    diesel:
      credit: kemptvillebest
      price: 169.9
      last_updated: "2025-03-31T19:37:14.761Z"
trend:
  average_price: 145.1
  lowest_price: 127.9
  area: Ottawa
```

I'll look into - how to save that **trend>average_price** and **trend>lowest_price** into a sensor later this week.

TBH, I've never worked with Templates before. I have to learn that :)

Thanks!

**Comment by firstof9** [comment]
> TBH, I've never worked with Templates before. I have to learn that :)

You can adapt the https://github.com/firstof9/ha-gasbuddy/issues/140#issuecomment-2769905388 template for your trends sensor.

**Comment by Dare2Code** [comment]
Hers's my code in Configuration.yaml file, and I'm getting 'Unknown' value. I've also restarted my Raspberry Pi, it's the same. any advice?

```
template:
  - trigger:
      - platform: time_pattern
        hours: /1
    action:
      - action: gasbuddy.lookup_zip
        data:
          zipcode: Ottawa, ON
          limit: 1
        response_variable: response
    sensor:
      - name: Average Gas Price (Regular)
        unique_id: average_gas_price_regular
        icon: mdi:gas-station
        unit_of_measurement: ¢
        state_class: measurement
        state: >
          {{ response.trend.average_price }}
      - name: Lowest Gas Price (Regular)
        unique_id: lowest_gas_price_regular
        icon: mdi:gas-station
        unit_of_measurement: ¢
        state_class: measurement
        state: >
          {{ response.trend.lowest_price }}
```

**Comment by tankdeer** [comment]
Unknown is probably ok. The sensors will be unknown until the first time pattern interval runs the action - apparently it doesn't do it when you reload templates. For testing purposes I had a 1 minute interval and it refreshed my sensors after a minute. After I knew it worked I changed it to my desired 4 hours

```
template:
  - trigger:
      - platform: time_pattern
        minutes: /1
...
```

**Comment by Dare2Code** [comment]
Awesome, I confirm it works now. Thanks.

**Comment by firstof9** [comment]
FYI guys:

```yaml
    - trigger: event
      event_type:
        - automation_reloaded
    - trigger: homeassistant
      event: start
```
