### ISSUE TITLE
[Feature Request]: Add a second last_updated

### ISSUE THREAD

**Issue by ldupont226** [firstof9/ha-gasbuddy#80]
### The feature

1 131 / 5 000
I will start by explaining my problem, to display the results of GasBoddy data I use custom:flex-table-card and that gives a good result. 
In this card we define the entities to search and then we specify the attributes for the columns. When we specify last_updated, it uses,by itself, the last_date (HA) of the entity and not the last_updated of the attribute. To get around the problem I rename the last_updated of your integration (sensor.py) by another name (ex: last_updated_gb) and it is well recognized. You could tell me to talk about my problem with the flex-table-card developers, it's true. But from another point of view, when using this card in other consistency it is practical to have the last_updated when there is no this attribute. Would it be to add another attribute with a different name than last_updated with the value of last_updated , I believe that the current last_updated must remain to be backwards compatible. If this is not possible I will continue to make the correction in sensor.py or if someone who uses flex-table-card has another solution.
Thanks

Here is an example of the result

![image](https://github.com/user-attachments/assets/c28e8d45-3cef-43a6-9cee-306f40c7b96e)

**Comment by firstof9** [comment]
"Last updated" is update per the timestamp provided by GasBuddy, I feel this is a proper use of the attribute as it shows when the last time someone submitted price data to GasBuddy.

**Comment by ldupont226** [comment]
As described in the previous message, there is no problem with your integration it works very well. 
But I use a popular card named flex-table-card which gives a very good result in Home Assistant. In this card we only name the attributes to see in column, but the NAME of your last_updated attribute is the same as Home Assistant and in this card (flex-table-card) it automatically takes the one of Home Assistant, But by using a card like Entities of Home assistant your Attribute works very well. To work around the problem I rename your Last_updated under another name in the sensor.py . When writing this request I suspected that it will probably be refused but if you or someone else uses flex-table-card with your integration have found a way to work around the problem. But if there was a second attribute under another name with the same information (last_updates) it would solve the problem. Yes indeed you can tell me that the problem is with flex-table-card ;-),
I can also continue to rename line 113 of sensor.py.

Thanks for your time

If you are interested you can try this card it gives a very nice look to your integration. If you try it pay attention to the Last_updated date


type: custom:flex-table-card
sort_by: friendly_name+
auto_format: false
clickable: true
entities:
  include:
    - sensor.*_regular_gas
  exclude:
    - sensor.*cash*
columns:
  - data: friendly_name
    name: Station
    icon: mdi:gas-station
  - data: state,unit_of_measurement
    name: Price
    icon: mdi:currency-usd
  - data: last_updated
    name: Last Update
    fmt: hours_mins_passed
    modify: if (x == null) {""} else {x}
css:
  table: 'padding: 0px 0px 0px 0px;'
  td: 'width: auto;white-space: nowrap;font-size: 11px'
  th: 'width: auto;white-space: nowrap;font-size: 14px'

**Comment by Dare2Code** [comment]
Instead of calling it a 'second last_updated' I believes its best to just say 'Date Prices posted by Gasbuddy' aka 'Date Posted'. Just saying.

**Comment by ldupont226** [comment]
When I write second last_updated, I'm not talking about the friendly name or description, I'm talking about another attribute with another name with the same information, different from the home assistant one. I wrote second because, for backwards compatibility reasons for everyone, the current last_updated field must remain. The name could be anything, different from 'last_updated'

**Comment by miked1313** [comment]
Great work on this integration!  Like @ldupont226 I would also like another last updated attribute such as `last_updated_gb` (in addition to it working like it does today with last_updated), so that I can use it with the custom:flex-table-card.

**Comment by miked1313** [comment]
Thank you for the quick change.  I updated to 1.0.17 and restarted HA.  Still didn't help the reported issue in the custom:flex-table-card and it broke mushroom chips.  Chips now show the wrong time when last updated is selected (time is really from last changed which is when HA restarted).

**Comment by miked1313** [comment]
@ldupont226 I was able to make the last version of this GasBuddy add-on work with an Entities card and the custom add-on `custom:multiple-entity-row` from https://github.com/benct/lovelace-multiple-entity-row. Only minor annoyance is you can't have a dynamic URL that fetches the station_id from the sensor state so they are hard coded which seems like an ok trade off to me since I wanted the relative timestamp of last updated from GasBuddy station last reported.  Card tap action is to open the GasBuddy web site and card hold action pops up more info in HA.

<img width="442" alt="image" src="https://github.com/user-attachments/assets/c24f94ae-a9d6-429d-bec7-3c54abfea2ee" />


```
type: entities
entities:
  - entity: sensor.costco_gas_regular_gas
    type: custom:multiple-entity-row
    name: Costco Gas
    tap_action:
      action: url
      url_path: https://www.gasbuddy.com/station/34567
    hold_action:
      action: more-info
    secondary_info:
      attribute: last_updated
      format: relative
  - entity: sensor.kroger_gas_loc1_regular_gas
    type: custom:multiple-entity-row
    name: Kroger Loc1
    tap_action:
      action: url
      url_path: https://www.gasbuddy.com/station/7890
    hold_action:
      action: more-info
    secondary_info:
      attribute: last_updated
      format: relative
  - entity: sensor.kroger_gas_loc2_regular_gas
    type: custom:multiple-entity-row
    name: Kroger Loc2
    tap_action:
      action: url
      url_path: https://www.gasbuddy.com/station/23456
    hold_action:
      action: more-info
    secondary_info:
      attribute: last_updated
      format: relative
  - entity: sensor.exxon_loc1_regular_gas
    type: custom:multiple-entity-row
    name: Exxon Loc1
    tap_action:
      action: url
      url_path: https://www.gasbuddy.com/station/12345
    hold_action:
      action: more-info
    secondary_info:
      attribute: last_updated
      format: relative
  - entity: sensor.exxon_loc2_regular_gas
    type: custom:multiple-entity-row
    name: Exxon Loc2
    tap_action:
      action: url
      url_path: https://www.gasbuddy.com/station/23094
    hold_action:
      action: more-info
    secondary_info:
      attribute: last_updated
      format: relative
```
